### PR TITLE
chore(itest): run babylond in e2e

### PR DESCRIPTION
**Pull request by Lazar955**
Run babylond in e2e tests
Remove tools
Run in parallel `15m` -> `4m`

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
We have kind of duplicated code in multiple babylon side car repositories for e2e testing, any way we could bring this code to Babylon package e2e as an exported functions and import from there? Since these repositories already depend on Babylon imports packages

**Comment by Lazar955** [comment]
> We have kind of duplicated code in multiple babylon side car repositories for e2e testing, any way we could bring this code to Babylon package e2e as an exported functions and import from there? Since these repositories already depend on Babylon imports packages

@RafilxTenfen yeah, I agree that ideally this would be reused among side car repos. Will create an issue (in pm repo?) to add `container` package to Babylon. So we would justify it as a testing framework for side cars.

But it shouldn't block the merging of this PR.

Wdyt @KonradStaniec?

**Comment by KonradStaniec** [comment]
>  yeah, I agree that ideally this would be reused among side car repos. Will create an issue (in pm repo?) to add container package to Babylon. So we would justify it as a testing framework for side cars.
> 

In general, I would prefer to keep Babylon node repo as minimal as possible, but given that alternative would be creating yet another repo for testing framework, I think I agree we can create separate package `container` in Babylon repo, and add readme there that it is a package to facilitate testing for programs which depends to Babylon. So 👍 on this from me.

**Review by KonradStaniec — APPROVED** [review]
Great job!

**Pull request merged**
